cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/media/Programming/CPRI_STUFF_LATEST/New/Thrust/NS3/ns-allinone-3.23/ns-3.23/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Tools/c_config.py", line 460, in run_c_code\n    bld.compile()\n  File "/media/Programming/CPRI_STUFF_LATEST/New/Thrust/NS3/ns-allinone-3.23/ns-3.23/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 140441006750096: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'-Wl,-Bsymbolic-functions\', \'-Wl,-z,relro\', \'test.cpp.1.o\', \'-o\', \'/media/Programming/CPRI_STUFF_LATEST/New/Thrust/NS3/ns-allinone-3.23/ns-3.23/build/.conf_check_3b2479b91ea1f8aedc2bbc867fa4858e/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/lib\', \'-lpython2.7\']\n'
